---
# configure kitchen driver in ~/.kitchen/config.yml or uncomment below:
#driver:
#  name: vagrant
#  customize:
#    memory: 1024

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-8

suites:
  - name: default
